name: Verify

on:
  pull_request: null
  push:
    branches:
    - master
    tags:
    - v*

jobs:
  build:
    runs-on: ubuntu-16.04
    name: OTP ${{matrix.otp}} / Elixir ${{matrix.elixir}}

    strategy:
      matrix:
        otp: [21.x, 22.x]
        elixir: [1.8.x, 1.9.x]
      fail-fast: false

    steps:
    - uses: actions/checkout@v1.0.0
      with:
        fetch-depth: 1
    - uses: actions/setup-elixir@v1.0.0
      with:
        otp-version: ${{matrix.otp}}
        elixir-version: ${{matrix.elixir}}
    - run: mix deps.get
    - run: mix test
